version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/circleci-workflows
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies
      - run: yarn install
      - save_cache:
          key: v1-dependencies
          paths:
            - node_modules
      - run: yarn docs:build
      - run: echo "start build static"

      - setup_remote_docker
      
      - run:
          name: build image by Dockerfile
          command: |
              docker build ./ -t ruaya/time-clock:1.0.0
      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push to docker hub
          command: |
              docker tag ruaya/time-clock:1.0.0 ruaya/time-clock:latest
              docker push ruaya/time-clock:latest