version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/circleci-workflows
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:cf:a5:58:e5:34:69:bb:c0:1f:bc:a6:e5:e6:64:0b"
      - checkout
      - run: yarn install
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn docs:build
      - run: echo "start build"
      - deploy:
          name: deploy
          command: |
            echo ${CIRCLE_BRANCH}
      - run: echo '部署完毕'
  deploy:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "在build之后进行"
workflows: 
  version: 2.1
  build_and_test1:
    jobs:
      - build
      - deploy:
          requires:
            - build
